const plugin = require('tailwindcss/plugin');

module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    colors: {
      'overlay-black': {
        1: 'var(--colors-overlay-black-1)',
        2: 'var(--colors-overlay-black-2)',
        3: 'var(--colors-overlay-black-3)',
        4: 'var(--colors-overlay-black-4)',
        5: 'var(--colors-overlay-black-5)',
        6: 'var(--colors-overlay-black-6)',
        7: 'var(--colors-overlay-black-7)',
        8: 'var(--colors-overlay-black-8)',
        9: 'var(--colors-overlay-black-9)',
        10: 'var(--colors-overlay-black-10)',
        11: 'var(--colors-overlay-black-11)',
        12: 'var(--colors-overlay-black-12)',
      },
      'overlay-white': {
        1: 'var(--colors-overlay-white-1)',
        2: 'var(--colors-overlay-white-2)',
        3: 'var(--colors-overlay-white-3)',
        4: 'var(--colors-overlay-white-4)',
        5: 'var(--colors-overlay-white-5)',
        6: 'var(--colors-overlay-white-6)',
        7: 'var(--colors-overlay-white-7)',
        8: 'var(--colors-overlay-white-8)',
        9: 'var(--colors-overlay-white-9)',
        10: 'var(--colors-overlay-white-10)',
        11: 'var(--colors-overlay-white-11)',
        12: 'var(--colors-overlay-white-12)',
      },
      'gray': {
        1: 'var(--colors-gray-1)',
        2: 'var(--colors-gray-2)',
        3: 'var(--colors-gray-3)',
        4: 'var(--colors-gray-4)',
        5: 'var(--colors-gray-5)',
        6: 'var(--colors-gray-6)',
        7: 'var(--colors-gray-7)',
        8: 'var(--colors-gray-8)',
        9: 'var(--colors-gray-9)',
        10: 'var(--colors-gray-10)',
        11: 'var(--colors-gray-11)',
        12: 'var(--colors-gray-12)',
      },
      'brand': {
        1: 'var(--colors-brand-1)',
        2: 'var(--colors-brand-2)',
        3: 'var(--colors-brand-3)',
        4: 'var(--colors-brand-4)',
        5: 'var(--colors-brand-5)',
        6: 'var(--colors-brand-6)',
        7: 'var(--colors-brand-7)',
        8: 'var(--colors-brand-8)',
        9: 'var(--colors-brand-9)',
        10: 'var(--colors-brand-10)',
        11: 'var(--colors-brand-11)',
        12: 'var(--colors-brand-12)',
      },
      'white': '#FFFFFF',
    },
    fontFamily: {
      primary: ['Inter'],
    },
    container: {
      center: true,
    },
    spacing: {
      0: '0',
      2: '0.125rem',
      4: '0.25rem',
      8: '0.5rem',
      12: '0.75rem',
      16: '1rem',
      20: '1.25rem',
      24: '1.5rem',
      28: '1.75rem',
      32: '2rem',
      40: '2.5rem',
      48: '3rem',
      56: '3.5rem',
      64: '4rem',
      72: '4.5rem',
      80: '5rem',
      96: '5.5rem',
      104: '6rem',
      112: '7rem',
      128: '8rem',
      144: '9rem',
    },
    fontSize: {
      12: ['0.75rem', '1rem'],
      14: ['0.875rem', '1.25rem'],
      16: ['1rem', '1.5rem'],
      18: ['1.125rem', '1.75rem'],
      20: ['1.25rem', '2rem'],
      24: ['1.5rem', '2.25rem'],
      32: ['2rem', '3rem'],
      40: ['2.5rem', '3.75rem'],
      56: ['3.5rem', '5.25rem'],
      72: ['4.5rem', '6.75rem'],
    },
    borderRadius: {
      2: '0.125rem',
      4: '0.25rem',
      8: '0.5rem',
      16: '16rem',
    },
    extend: {},
  },
  plugins: [],
};
